Controllers/ManageshopController.cs
using clothingshopproject.Database;
using clothingshopproject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace clothingshopproject.Controllers
{
    [Authorize]
    public class ManageshopController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ManageshopController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public IActionResult Index()
        {
            IEnumerable<Clothingshop> objList = _db.Clothingshop;
            return View(objList);
        }
        //Get create
        public IActionResult Create()
        {
           ViewBag.Size = new List<string>() { "S", "L" ,"M","XL","XXL" };

            return View();
        }
        //post create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Clothingshop obj)
        {
            if (ModelState.IsValid)
            {
                _db.Clothingshop.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }


        //Get Edit
        public IActionResult Edit(int? Id)
        {
            ViewBag.Size = new List<string>() { "S", "L", "M", "XL", "XXL" };
            if (Id==null || Id==0)
            {
                return NotFound();
            }
            var obj = _db.Clothingshop.Find(Id);
            if (obj==null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Clothingshop obj)
        {
            if (ModelState.IsValid)
            {
                _db.Clothingshop.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }
        //Get Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Clothingshop.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deletepost(int? Id)

        {
            var obj = _db.Clothingshop.Find(Id);
            if (obj==null)
            {
                return NotFound();
            }
            
                _db.Clothingshop.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
           

            
        }
    }
}

Views/Shared/Logininfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager

@if (_signInManager.IsSignedIn(User))
{
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello  @User.Identity.Name
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a>
            <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">Change Password</a>

        </div>
    </div>
}
else
{
<li class="nav-item">
    <a class="btn btn-outline-primary" asp-controller="Account" asp-action="login">LogIn</a>
    <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Signup">Register</a>
</li>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - clothingshopproject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-warning" asp-area="" asp-controller="Home" asp-action="Index">Fahad Clothing Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <partial name="LoginInfo" />
                    </ul>
                



                
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Manageshop" asp-action="Index">ProductsDetails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" bg-dark border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Clothing Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>